@extends('layouts.app') 
@section('title', 'Terms and Conditions')
@section('content')

<section class="">
        <h1 class="text-3xl md:text-4xl font-bold  mb-8 text-center bg-secondary py-6">Terms & Conditions</h1>
         
        <div class="max-w-7xl mx-auto px-4 py-2 md:py-6 space-y-6 text-textBlack text-base md:text-lg leading-relaxed text-justify">
            <p>
                These Terms and Conditions (“Terms”) govern access to and use of the website, platform, assessments, reports, and related services (“Services”) provided by Udyantra (“Company”, “we”, “us”, or “our”).
            </p>

            <p class="font-medium">
                By accessing or using the Services, you agree to be legally bound by these Terms.
            </p>

            <div class="space-y-6 mt-8">
                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">1. Scope of Services</h2>
                    <p>
                        Udyantra provides psychometric assessments and analytical reports based on established psychological theories, validated methodologies, and academic research attributed to renowned psychologists and institutions. The Services are offered to educational institutions, individuals, parents, and professionals for informational and guidance purposes only.
                    </p>
                </div>

                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">2. No Professional Advice</h2>
                    <p>
                        The assessments, insights, and reports generated by Udyantra do not constitute medical, psychological, psychiatric, or professional career advice. Udyantra does not guarantee specific outcomes, academic success, admissions, or career placements. Users are advised to seek qualified professional consultation where required.
                    </p>
                </div>

                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">3. User Eligibility and Consent</h2>
                    <p>
                        Users must be legally competent to enter into a binding contract. For users under 18 years of age, usage is permitted only with verifiable consent from a parent, legal guardian, or authorized school representative. Institutions using the platform confirm that appropriate permissions have been obtained.
                    </p>
                </div>

                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">4. Account Responsibility</h2>
                    <p>
                        Users are responsible for maintaining the confidentiality of login credentials and for all activities conducted through their account. Udyantra shall not be liable for unauthorized access arising from user negligence.
                    </p>
                </div>

                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">5. Intellectual Property Rights</h2>
                    <p>
                        All assessments, content, reports, scoring models, trademarks, and proprietary methodologies are the exclusive intellectual property of Udyantra. No part of the Services may be copied, modified, redistributed, reverse-engineered, or commercially exploited without prior written consent.
                    </p>
                </div>

                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">6. Data Protection and Confidentiality</h2>
                    <p>
                        User data is collected, stored, and processed in accordance with applicable data protection laws and Udyantra’s Privacy Policy. Assessment data is treated as confidential and shall not be shared with third parties except as required by law or with user consent.
                    </p>
                </div>

                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">7. Limitation of Liability</h2>
                    <p>
                        To the maximum extent permitted by law, Udyantra shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in connection with the use of the Services or reliance on assessment results.
                    </p>
                </div>

                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">8. Indemnification</h2>
                    <p>
                        Users agree to indemnify and hold harmless Udyantra from any claims, damages, losses, or liabilities arising from misuse of the Services or violation of these Terms.
                    </p>
                </div>

                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">9. Modification and Termination</h2>
                    <p>
                        Udyantra reserves the right to modify, suspend, or discontinue any part of the Services or these Terms at its discretion. Continued use of the Services constitutes acceptance of updated Terms.
                    </p>
                </div>

                <div>
                    <h2 class="text-xl font-bold text-primary mb-2">10. Governing Law and Jurisdiction</h2>
                    <p>
                        These Terms shall be governed by and construed in accordance with the laws of India. Courts located in India shall have exclusive jurisdiction over any disputes.
                    </p>
                </div>
            </div>
        </div>
</section>

@endsection